eureka:
#  instance:
#    metadata-map:
#      user.name: "${security.user.name}"
#      user.password: "${security.user.password}"
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

server:
  port: 5005

logging:
  file: "logs/boot-admin-sample.log"


spring:
  application:
    name: service-admin
  boot:
    admin:
#      username: "${security.user.name}"      #These two are needed so that the client
#      password: "${security.user.password}"   #can register at the protected server api
#      client:
#        metadata:
#          user.name: "${security.user.name}"
#          user.password: "${security.user.password}"
      turbine:
        clusters: default
        location: service-turbine
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti

#security:
#  user:
#    name: admin
#    password: 123456
#  basic:
#    enabled: false
