eureka:
#  instance:
#    metadata-map:
#      user.name: "${config.user.name}"
#      user.password: "${config.user.password}"
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  security:
    enabled: true

server:
  port: 5005

logging:
  file: "logs/boot-admin-sample.log"


spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: service-admin
  boot:
    admin:
      username: root
      password: 123456
      client:
        metadata:
          user:
            name: admin
            password: 123456
      turbine:
        clusters: default
        location: service-turbine
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti

security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: false
