eureka:
  instance:
    prefer-ip-address: true
#    appname: eureka-client
#    hostname: eureka-client
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8764

spring:
  application:
    name: eureka-client


logging:
  file: "logs/eureka-client-two.log"


management:
  security:
    enabled: false
