eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 5000

spring:
  application:
    name: service-zuul

zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
#      url: http://localhost:8763
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
#  prefix: /v1

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true


#zuul:
#  routes:
#    xxapi:
#      path: /xxapi/**
#      serviceId: xxapi-v1
#ribbon:
#  eureka:
#    enabled: false
#xxapi-v1:
#  ribbon:
#    listOfServers: http://localhost:8763,http://localhost:8764
