eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 9412

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true



security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5008/uaa/users/current
    client:
      access-token-uri: http://localhost:5008/uaa/oauth/token
      id: uaa-service
      client-secret: 123456
      grant-type: client_credentials,password
      scope: server

