
spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8765
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
