eureka:
  instance:
    prefer-ip-address: true
    appname: eureka-client
    hostname: eureka-client
    virtual-host-name: eureka-client
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 9999

spring:
  application:
    name: eureka-client
