eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8769

spring:
  application:
    name: eureka-client-one

logging:
  file: "logs/eureka-client-one.log"

management:
  security:
    enabled: false
