eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  security:
    enabled: false


server:
  port: 5001

logging:
  file: "logs/boot-admin-sample.log"

spring:
  application:
    name: service-admin
  boot:
    admin:
      turbine:
        clusters: default
        location: service-turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
