eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 9414

spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            test:
#              - uri: http://localhost:9414
#                metadata:
#                  management.context-path: /actuator
#              - uri: http://localhost:9414
#                metadata:
#                  management.context-path: /actuator
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: test
        url: http://localhost:5001
  application:
    name: admin-client

logging:
  file: "logs/eureka-client-one.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"


info:
  tags:
    environment: test
