
spring:
  application:
    name: eureka-feign-client

server:
  port: 8766
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true
#  httpclient:
#    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
