
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuluhuang/spring-boot-cloud-demo.git
          search-paths: respo
          username: 504367857@qq.com
          password:
      label: master
#        native:
#          search-locations: classpath:/shared

  profiles:
    active: native
  application:
    name: config-server


server:
  port: 8768
