
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuluhuang/spring-boot-cloud-demo
          search-paths: config
          username:
          password:
      label: master
#        native:
#          search-locations: classpath:/shared

  profiles:
    active: native
  application:
    name: config-server


server:
  port: 8768

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
